### PR TITLE
created project card anatomy file

### LINKED ISSUE #128: Project Card Anatomy
### Overview
Create a guide for the project card anatomy so it can be clear for users.

### Action Items
Create a guide for the project card anatomy with screenshots and explanation.

### Resources/Instructions
[Figma ](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=248%3A7443)

### PR DESCRIPTION
**Pull request by superbunker**
---
title: Project Card Anatomy
description: Explanation of all the elements on the project cards
status: Active
display: true
---

# Project Card Anatomy

project card anatomy image

## Project Image
A [unique image](https://github.com/100Automations/Website/blob/gh-pages/_guides/creating-good-readmes-for-automations.md) to identify and describe the project
link: good image guide

## Help Needed status
If the project needs a specific type of assistance, it will be listed here
 - Needs Maintenance
 - Needs Support For Users
 - Needs Refactoring
 - Needs Documentation
 - Needs Peer Review
 - Needs To Be Built
 - Needs To Be Researched
 - Needs Advice
 - Needs Takeover
 - Advice Needed

## Languages and frameworks Used
A list of the technologies used to create the project, and the skills that could be useful for contributors

## Status of Project
The stage of the project's development
 - In Use And Ready To Deploy
 - In Use And Being Refactored
 - Ready To Deploy
 - In Development
 - Ready For Development
 - In Ideation
 - Abandoned

## Description
A brief overview of the project, what it does, what problem it tries to address, and how it solves it.

## Github ReadMe Link
This goes the "readme" file at the GitHub code hosting platform. The readme provides a more in-depth description of the automation, with an overview of the technical details.

## Codebases project is used by
These or projects and organizations that are currently using the automation, identified by logo

---
_End of Guide_
To propose/submit changes, please [edit](https://github.com/100Automations/Website/blob/master/_guides/project-card-anatomy.md) the markdown file for this guide

### CODE REVIEW

**Comment by superbunker** [comment]
fixes #128

**Review by henlatourrette — CHANGES_REQUESTED** [review]
Hi @superbunker , I was checking your file but it seems to be empty. I see that you put a content in the comment on this pull request but maybe you wanted to put that comment inside the file you intend to merge. Can you please check that and confirm back? Thanks!

**Comment by superbunker** [comment]
@henlatourrette   Yep, pasted in the wrong spot. 
Should be the there now.

**Review by henlatourrette — APPROVED** [review]
Great, this one is working!

**Pull request merged**
