### PR TITLE
Issue #146 - Created a button for the Automation Card

### PR DESCRIPTION
**Pull request by stellaliao01**
## Types of changes

- [ ] Bugfix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Refactor (change which changes the codebase without affecting its external behavior)
- [x] Non-breaking change (fix or feature that would causes existing functionality to work as expected)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
## Purpose

Added styling for the button in the Automation Card
## Approach

-Followed Figma styling for the button
-added links for Font awesome (github logo) and font for poppins for the text
## Screenshot(s)

Screen Shot 2021-02-08 at 10 35 26 PM

### CODE REVIEW

**Comment by Olivia-Chiong** [comment]
@drubgrubby could we get your eyes on this PR as well please? Thank you

**Review by drubgrubby — COMMENTED** [review]
@stellalia01 - The button looks great on visual review. Nice work.  

However, before I review the code on your pull request, I want to ask some questions about the PR itself.

1) It seems like are are requesting to merge the branch containing your changes (stellaliao01:master) into the branch 100Automations:mdothman.  It seems to me that the changes should be merged into gh-pages. 
2) This PR has 24 files changed in it, and most of those don't seem to have anything to do with the lovely blue button.  Is that intentional? 

There are two commits here. It seems to me like the second one are the three files that you changed for your button - ato_grid.html, head.html, ato_grid.scss.  The first commit -  "Merge branch 'mdothman' of https://github.com/100Automations/Website" seems to have a bunch of other changes that don't seem relevant.  It seems like this PR should be just the changes for the button. 

Usually when I see that it's because someone branched from a previous branch that they had already been working on when starting a new issue, rather than branching from a clean, updated gh-pages.  

It's possible that I don't understand something here;  It wouldn't be the first time.  

So, I'd suggest either submitting a new, clean PR, or, if I'm not understanding something here, please let us know a) why this is being merged into 100Automations:mdothman and, b) the reason for the changes to the additional 21 files. 

(Again, the button looks really nice and I'm looking forward to reviewing the code for it).

**Comment by stellaliao01** [comment]
@drubgrubby - Those are great questions. 

During a meeting, Dean and I came to the conclusion to merge with Dean's branch since his work had not been pushed to gh-pages. @mdothman (let me know if that's correct, I thought it was what we discussed but maybe there was miscommunication). I believe those 24 file changes are Dean's which is why they're showing up because they're different from the main branch. 

Let me know your thoughts, I will gladly do another PR but don't want to take credit for Dean's 24 file changes.

**Comment by drubgrubby** [comment]
@stellaliao01 - Thanks for your response, and good to know that it was intentional.  

It sounds like there's a master-plan for doing these two things - merging with a branch other than gh-pages, and having the other files be part of this PR - but since I don't know what it is, I'm just going to share my general thoughts. The 100Automations team can then do what you will

1) As far as merging into 100Automations:mdothman, if you discussed it in a meeting, them I'm assuming that there's a reason for this and that it's fine. I'm assuming that @mdothman will confirm that when he reviews this PR.

2) In general, I find it helpful to put as much information into the PR an/or the issue as possible. This is really a kindness to the person reviewing the PR.  When I have to spend a lot of time figuring out why someone did something, when then could have just said "I'm doing this thing for this reason", it makes me a little cranky. (Just a little).  

For example, in this PR you could have said, "These three files are the changes to the button.  The other files are included in this PR for the following reason...".  It just saves time in the back-and-forth of PR reviewing, and let's the reviewer have more confidence that they know exactly what you intended, so they can know if it's working. 

It's just like commenting code, it just helps the person coming along behind you to figure out what's going on as quickly as possible. 

3) In my opinion, this PR should just include your changes to the button, and any other changes should be on their own PR.  The reason for this is mainly that by merging all of the changes from @mdothman 's branch here, there's no way to properly review them before merging.  I'm not sure what issue they are addressing, so I have no idea how to decide if it is okay to merge them or not.  

For example, some of these changes are to footer.html.  Matthew's PR that I just reviewed also makes a bunch of changes to the footer.  If Matthew's gets pushed moving the issue forward, and then this gets pushed after, does it move it back again to an earlier stage?  I don't know, but it would be easier to test that on its own rather than having it tied to your button issue. 

As I said, there may be a master plan that I don't know anything about and this is all just fine.  But in general, I find the smaller and more surgical the issue and the PR are, the easier it is to confidently push them through the system.

**Comment by drubgrubby** [comment]
All of that said, the commit that contains the button changes looks great, and I would certainly approve those files to merge if they were on their own PR.  Very nice work!

**Comment by stellaliao01** [comment]
Ah I understand now, thank you for the feedback. I apologize for the back and forth. I can make a new PR tonight to make this easier.

**Pull request closed without merging**
