### PR TITLE
Dropdown list

### LINKED ISSUE #162: Create a dropdown for needs help button on automation cards
### Overview
Each Automation card needs the button in upper lefthand corner to dropdown list of all roles that are needed on the project.

### Action Items
- [x] Make button clickable, and list hidden when page loads.
- [x] Add list of 'needs help' roles that toggles when button is clicked. 

### Resources/Instructions
Use Figma if needed.

Screen Shot 2021-02-20 at 8 49 13 AM

### PR DESCRIPTION
**Pull request by mcspach**
Fixes #162
-'needs help' button is placed above the full automation card.
-clicking the button triggers the list of open roles to be shown or hidden.

### CODE REVIEW

**Comment by mdothman** [comment]
I've reviewed the code and think that you did a great job on the needs list. I especially like how you created a javascript toggle function. The display none seems to be the only conflict with Material Design Lite framework, which is great. I just need some screenshots of your development.

**Comment by NivenPrasad** [comment]
@mcspach let's change status of this to draft while you're reworking it and then back as a pull request when you're ready.

**Comment by akibrhast** [comment]
I am converting it to draft since it's been three days, and has not yet been converted to a draft.

**Comment by Olivia-Chiong** [comment]
@mcspach wanted to review and merge this, but found there is a conflict. Can you please take a look?

@akibrhast I've requested you do a review on the code as well. Thanks!

**Comment by mcspach** [comment]
@Olivia-Chiong I resolved the conflict and updated the request, it is now safe to merge without conflict.

**Pull request merged**
