### PR TITLE
true-github-contributors added

### LINKED ISSUE #31: Create automation card for True GitHub Contributors
### Overview
Provide collateral for the OpenSourceAutomations.org website

### Action Items
- [x]   Gather items
  - [x]  600 x 400 image
     - [x]  Alt image text
  - [x]  Name of automation
  - [x]  A blurb about the automation
  - [x]  Links (github, slack channel url, Testing Site, Live Site, etc.)
  - [x] Healthy project files (see resources for instructions)
     - [x]  Readme.md URL
     - [x]  contributing.md URL
     - [x]  security.md URL
     - [x]  support.md URL
  - [x] Current status of Automation
     - [ ] in use and ready to deploy
     - [x] in use and being refactored
     - [ ] ready to deploy
     - [ ] in development
     - [ ] ready for development
     - [ ] in ideation
     - [ ] abandoned
  - [x] If status in use, what codebase can it be seen in?
   - [x] Help wanted (check all that apply)
     - [ ] needs maintenance
     - [ ] needs support for users
     - [ ] needs refactoring
     - [ ] needs documentation 
     - [x] needs peer review
     - [ ] needs to be built
     - [ ] needs to be researched
     - [ ] needs advice
     - [ ] needs takeover
        - [ ] Advice Needed: (type in sort description of what you need)
- [x]   Add automation Card to website

### Resources/Instructions
See project cards on the hackforla.org website for general idea, although the format of these will be different.

- [GitHub's guide: Setting guidelines for repository contributors](https://docs.github.com/en/articles/setting-guidelines-for-repository-contributors)
- [GitHub's guide: Adding a security policy to your repository
](https://docs.github.com/en/articles/adding-a-security-policy-to-your-repository)
- [GitHub's guide: Adding support resources to your project
](https://docs.github.com/en/articles/adding-support-resources-to-your-project)

**Readme should include:**
- Overview 
  - _What kind of repetitive thing do you have to do often and what is the benefit of automating it?_
- Current State 
  - _"As-is" most likely something manual but could be partially automated_
- Future Development
  - _The “To-be” state_
- Stakeholders
  - _Impact - who benefits and how?_
- Anticipated outcomes
- Resources/Instructions
  - _How to run the automation and any packages or dependencies_ 
- Language
  - _Programming language(s)_
- Platform
  - _Where is it deployed (e.g. GitHub, Linux Command Line, Windows Command Line etc)_
- Automation triggers 
  - _What starts it? What's it responding to?
  - _Is it Time-based (Specify frequency (e.g. 1x/week)?_
  - _Is it Event-based (e.g. someone just created a new GitHub on a repo)?_
- Input required 
  - _How much manual or custom input is required?_
- Output 
  - _What's the desired result? What do we not want to see?_

### PR DESCRIPTION
**Pull request by mcspach**
Fixes #31

-new md file for true github contributors
-populated with all links and info for the automation
-image added to assets folder

this section will need css adjustments.

### CODE REVIEW

**Review by akibrhast — CHANGES_REQUESTED** [review]
Please add the author name 
linkedin: https://www.linkedin.com/in/kian-badie-1b8829151/
github: @KianBadie

**Comment by mcspach** [comment]
@akibrhast @Olivia-Chiong I added @KianBadie as the author in the automation md. 

Jekyll-GDT has a line for a slack link but that link is broken. Im not even sure if you can have a link to a specific user profile on Slack, only to a workspace or channel. Do you want me to add a Slack link? It is currently commented out.

If its all good, can I please have this merged and then I will move on to the CSS?
Thanks!

**Comment by mcspach** [comment]
If there was something that needs to be changed here, I forgot. As far as I know it's ready to be merged. 
Last meeting we decided Slack links were not necessary so there is no changes needed. 
It would be very helpful to have this branch merged for styling the automation card layout.

**Comment by mcspach** [comment]
@NivenPrasad sorry I couldn't be at the meeting yesterday. Is there some reason this hasn't been merged yet? The question about Slack link was answered in the meeting last week but for some reason this is still waiting to be merged.

**Pull request merged**
